services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    labels:
      glance.name: Jellyfin
      glance.icon: sh:jellyfin
      glance.description: Movies & shows
      glance.url: http://${URL}:8096
    user: "1000:1000"
    ports:
      - "8096:8096"  # host:container
    volumes:
      - ./jellyfin:/config
      - ./.cache/jellyfin:/cache
      - /home/richard/Videos:/media
    restart: unless-stopped
    env_file: .env

