include:
  - arr/docker-compose.yml
  - glance/docker-compose.yml
  - immich/docker-compose.yml
  - media/docker-compose.yml
  - paperless/docker-compose.yml
  - romm/docker-compose.yml
  - docker-compose.network.yml
  - docker-compose.vaultwarden.yml
