services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    labels:
      glance.name: qbittorrent
      glance.icon: sh:qbittorrent
      glance.description: Torrent client
      glance.url: http://${URL}:9090
    ports:
      - "9090:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORTS=8080/tcp,8080/udp
      - LIBTORRENT=v1
      - UNBOUND_ENABLED=true
      - UNBOUND_NAMESERVERS=194.242.2.2@853,194.242.2.4@853
    volumes:
      - ./qbittorrent:/config
      - ./data:/data
    dns:
      - 127.0.0.1

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    labels:
      glance.name: Prowlarr
      glance.icon: sh:prowlarr
      glance.description: Indexer
      glance.url: http://${URL}:9696
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
      - UNBOUND_ENABLED=true
      - UNBOUND_NAMESERVERS=194.242.2.2@853,194.242.2.4@853
    volumes:
      - ./prowlarr:/config
      - ./data:/data
    dns:
      - 127.0.0.1

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    labels:
      glance.name: Radarr
      glance.icon: sh:radarr
      glance.description: Movie Indexer
      glance.url: http://${URL}:9696
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
      - UNBOUND_ENABLED=true
      - UNBOUND_NAMESERVERS=194.242.2.2@853,194.242.2.4@853
    volumes:
      - ./radarr:/config
      - ./data:/data
    dns:
      - 127.0.0.1
