services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    labels:
      glance.name: Jellyfin
      glance.icon: si:jellyfin
      glance.description: Movies & Shows
      glance.url: http://${URL}:8096
    user: "1000:1000"
    ports:
      - "8096:8096"  # host:container
    volumes:
      - ./jellyfin:/config
      - ./.cache/jellyfin:/cache
      - /home/richard/Videos:/media
    restart: unless-stopped
    env_file: .env

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    labels:
      glance.name: Audiobookshelf
      glance.icon: si:audiobookshelf
      glance.description: Audiobooks & Podcasts
      glance.url: http://${URL}:13378
    ports:
      - 13378:80
    volumes:
      - ${AUDIOBOOKS}:/audiobooks
      - ${PODCASTS}:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    environment:
      - TZ=${TZ}

