- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: group
          widgets:
            - type: weather
              title: Chester
              location: Chester, United Kingdom
              units: metric # alternatively "imperial"
              hour-format: 24h # alternatively "24h"           
            - type: weather
              title: Blackpool
              location: Blackpool, United Kingdom
              units: metric # alternatively "imperial"
              hour-format: 24h # alternatively "24h"
            - type: weather
              title: London
              location: London, United Kingdom
              units: metric # alternatively "imperial"
              hour-format: 24h # alternatively "24h"
        - type: bookmarks
          groups:
          - links:
            - title: Moodle
              url: https://moodle.chester.ac.uk/my/
              icon: si:moodle
            - title: Timetable
              url: https://timetabling.chester.ac.uk/personal
              icon: si:googlecalendar
            - title: Portal
              url: https://portal1.chester.ac.uk/Pages/default.aspx
              icon: si:dotnet

    - size: full
      widgets:
        - type: docker-containers
          running-only: true

        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true

    - size: small
      widgets:
        - type: server-stats
          servers:
            - type: local
              name: Services

        #taken from yahoo finance
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: NQ=F
              name: Nasdaq 100
            - symbol: BTC-GBP
              name: Bitcoin
            - symbol: ETH-GBP
              name: Ethereum


        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - go-gitea/gitea
            - immich-app/immich
            - syncthing/syncthing