services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    labels:
      glance.name: qBittorrent
      glance.icon: si:qbittorrent
      glance.description: Torrents
      glance.category: System
      glance.url: http://${URL}:9090
    ports:
      - "9090:8080"
    environment:
      - LIBTORRENT=v1
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ${DATA}/qbittorrent:/config
      - ${MEDIA}:/media
    dns:
      - 127.0.0.1
    env_file: hotio.env
    restart: unless-stopped

