services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    labels:
      glance.name: qBittorrent
      glance.icon: si:qbittorrent
      glance.description: Torrents
      glance.url: http://${URL}:9090
    ports:
      - "9090:8080"
    environment:
      - LIBTORRENT=v1
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ${DATA}/qbittorrent:/config
      - ${MEDIA}:/media
    dns:
      - 127.0.0.1
    env_file: hotio.env
    restart: unless-stopped


  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    labels:
      glance.name: Prowlarr
      glance.icon: si:bittorrent
      glance.description: Indexer
      glance.url: http://${URL}:9696
    ports:
      - "9696:9696"
    volumes:
      - ${DATA}/prowlarr:/config
      - ${MEDIA}:/media
    dns:
      - 127.0.0.1
    env_file: hotio.env
    restart: unless-stopped


  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    labels:
      glance.name: Radarr
      glance.icon: si:radarr
      glance.description: Film Indexer
      glance.url: http://${URL}:7878
    ports:
      - "7878:7878"
    volumes:
      - ${DATA}/radarr:/config
      - ${MEDIA}:/media
    dns:
      - 127.0.0.1
    env_file: hotio.env
    restart: unless-stopped

